# Scitos Mira
scitos_mira:
  ros__parameters:
    modules: ['Charger', 'Drive']
    config_file: "resources/CLARC/SCITOSDriver.xml"
    magnetic_barrier_enabled: true
    odometry_frame: base_footprint
