# Scitos Mira
scitos_mira:
  ros__parameters:
    modules: ['Charger', 'Drive']
    drive:
      base_frame: base_link
      magnetic_barrier_enabled: true
      publish_tf: true
      reset_bumper_interval: 1000

