# Simple set of rules for GitHub actions integration with a ROS project
#

name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Download and extract MIRA
        run: |
            curl -o mira.tar.gz https://www.mira-project.org/downloads/MIRA-2023-12-15_r10375.tar.gz
            tar -zxvf mira.tar.gz
            rm mira.tar.gz
      - name: Install MIRA
        run: |
            cd MIRA
            export MIRA_PATH=$(pwd)
            make
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: rolling
      - name: Install dependencies
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: scitos2
          target-ros2-distro: rolling
          colcon-defaults: |
            {
              "build": {
                "mixin": ["coverage-gcc", "coverage-pytest"]
              },
              "test": {
                "mixin": ["coverage-pytest"]
              }
            }
          skip-tests: false
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ros_ws/lcov/total_coverage.info,ros_ws/coveragepy/.coverage
          flags: unittests
          name: codecov-umbrella
          slug: grupo-avispa/scitos2
